const links = {
  about: "",
  Appstore: "",
  blog: "",
  buy_plan: "",
  contact: "",
  coverage: "",
  Cookies_policy: "",
  dashboard: "",
  faq: "",
  facebook: "",
  home: "",
  info: "mailto:info@interlan.pe",
  instagram: "",
  Internet_use_policy: "",
  institutional: "",
  Itl: "http://Itl.com.pe",
  linkedin: "",
  login: "",
  mail: "mailto:cvemo@interlanperu.com",
  MTC: "",
  my_portal: "",
  neutrality_regulation: "",
  osiptel: "",
  Payment_methods: "",
  Playstore: "",
  payment: "",
  plans: "",
  pronatel: "",
  promotions: "",
  reclaimbook: "",
  reclaims: "",
  reclaims_directive: "",
  return_interruption: "",
  rights: "",
  signup: "",
  social_media_privacy_policy: "",
  terminosycondiciones: "",
  twitter: "",
  use_conditions: "",
  website_privacy_policy: "",
  Website_Terms_of_Use: "",
  we: "",
  youtube: "",
};

export default links;
